---
title: "Textbook Example"
author: "Carter Sun"
date: "9/26/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)

year <- 2020
quarters <- 1:4
type <- "Electric"

pge_20_elec <- NULL

for(quarter in quarters) {
  filename <- 
    paste0(
      "PGE_A1/CSVs/pge/PGE_", 
      year, 
      "_Q", 
      quarter, 
      "_", 
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_20_elec <- rbind(pge_20_elec,temp)
  # Note rbind requires field names to be consistent for every new thing that you add.

  saveRDS(pge_20_elec, "pge_20_elec.rds")
}
```

```{r}
library (tidyverse)
pge_filter <- filter(pge_20_elec, CUSTOMERCLASS %in% c("Elec- Residential", "Elec- Commercial"))

```

```{r}
pge_select <- select(pge_filter, -YEAR, -COMBINED, -AVERAGEKWH)
pge_group <- group_by(pge_select, MONTH, CUSTOMERCLASS)
pge_summarize <- summarize(pge_group, TOTALKWH = sum(TOTALKWH, na.rm = T))

```

```{r}
pge_wide <- pivot_wider(pge_summarize, names_from = CUSTOMERCLASS, values_from = TOTALKWH)
pge_wide
```
```{r}
pge_tidy <- pivot_longer(pge_wide, c("Elec- Commercial","Elec- Residential"), names_to = "CUSTOMERCLASS", values_to = "TOTALKWH")

pge_tidy
```
```{r}
pge_summarize <- summarize(pge_group, TOTALKWH = sum (TOTALKWH, na.rm = T), TOTALCUSTOMERS = sum(TOTALCUSTOMERS, na.rm = T))
pge_mutate <- mutate(pge_summarize, AVERAGEKWH = TOTALKWH/TOTALCUSTOMERS)

```

```{r}
pge_final <-
  pge_20_elec %>% 
  filter(
    CUSTOMERCLASS %in% 
           c("Elec- Residential", "Elec- Commercial")
    ) %>% 
  select (!c(YEAR,COMBINED,AVERAGEKWH)) %>%
  group_by(MONTH, CUSTOMERCLASS) %>% 
  summarize(
    TOTALKWH = sum (TOTALKWH, na.rm = T),
    TOTALCUSTOMERS = sum(TOTALCUSTOMERS, na.rm = T)
  ) %>% 
  mutate(AVERAGEKWH = TOTALKWH/TOTALCUSTOMERS)
pge_final
```


```{r}
pge_chart <- 
  pge_final %>% 
  ggplot() + geom_bar(
    aes(
      x = MONTH %>% factor(),
      y = TOTALKWH,
      fill  = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs (
    x = "Month",
    y = "kWh",
    title = "PG&E Territory Monthly Electricy Usage, 2019",
    fill = "Electricity Type"
  )

pge_chart %>% 
  ggplotly() %>% 
  layout(
    xaxis = list(fixedrange = T),
    yaxis = list(fixedrange = T)
  ) %>% 
  config(displayModeBar = F)

pge_chart
```

```{r}
#TEST CODE
library(tidyverse)
library(ggplot2)

years <- 2017:2020
quarters <- 1:4
categories <- 1:2
type <- "Electric"

pge_elec <- NULL
pge_gas <- NULL
for (category in categories) {
  for (year in years) {
    for(quarter in quarters) {
      filename <- 
        paste0(
          "PGE_A1/CSVs/pge/PGE_", 
          year, 
          "_Q", 
          quarter, 
          "_", 
          type,
          "UsageByZip.csv"
        )
    
      print(filename)
      temp <- read_csv(filename)
      if (type == "Electric") {
        pge_elec <- rbind(pge_elec,temp)
        saveRDS(pge_elec, "pge_elec.rds")
      }
      else {
        pge_gas <- rbind(pge_gas,temp)
        saveRDS(pge_gas, "pge_gas.rds")
      }
    }
  }
  type = "Gas"
}


```
